# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-referenc
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
         command: docker build -t $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast.amazonaws.com/nginx-sample-webapp:$CIRCLE_SHA1 .
  test:
    machine: true
    steps:
      - checkout
      - run:
          command: docker run -d -p 80:80 --name nginx-sample-webapp $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/nginx-sample-webapp:$CIRCLE_SHA1
